/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhDotsThreeVertical: typeof import('~icons/ph/dots-three-vertical')['default']
    IPhGear: typeof import('~icons/ph/gear')['default']
    IPhGlobe: typeof import('~icons/ph/globe')['default']
    IPhListHeart: typeof import('~icons/ph/list-heart')['default']
    IPhMinus: typeof import('~icons/ph/minus')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhPlus: typeof import('~icons/ph/plus')['default']
    IPhPresentationChart: typeof import('~icons/ph/presentation-chart')['default']
    IPhQuestion: typeof import('~icons/ph/question')['default']
    IPhRocketLaunch: typeof import('~icons/ph/rocket-launch')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.1.0_@babel+parser@7.26.7_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.3_@t_ca456f90b47d31e76cfaf344355cf545/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
